import {
  Sparkles,
  Wind,
  Flame,
  Flower2,
  Leaf,
  Droplet,
  Gem,
  Flag,
  Home,
  Landmark,
  TreePine,
  Building2,
  Heart,
  Sun,
  Shuffle,
  Shirt,
  Hand,
  Clock,
  BadgeCheck,
  Rabbit,
  Scale,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react';

const map: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  wind: Wind,
  flame: Flame,
  flower: Flower2,
  leaf: Leaf,
  droplet: Droplet,
  gem: Gem,
  flag: Flag,
  home: Home,
  landmark: Landmark,
  tree: TreePine,
  building: Building2,
  heart: Heart,
  sun: Sun,
  shuffle: Shuffle,
  shirt: Shirt,
  hand: Hand,
  clock: Clock,
  'badge-check': BadgeCheck,
  rabbit: Rabbit,
  scale: Scale,
  'shield-check': ShieldCheck,
};

export function getIcon(name: string): LucideIcon {
  return map[name] ?? Sparkles;
}
